import type { Asset, CascadeLink } from '@/types';

// CityPulse 4D — Realistic dummy data matrix
// 15+ assets across 5 categories with linked dependencies, cost breakdowns,
// telemetry, barrier states, RQI segments, near-miss/pole-strike events.

export const ASSETS: Asset[] = [
  // ---------- DRAINS ----------
  {
    id: 'D-102',
    category: 'drain',
    name: 'Drain D-102',
    ward: 'Ward 4 — Riverside',
    location: { x: 30, y: 58 },
    ageYears: 14,
    material: 'RCC Box Culvert',
    installedYear: 2011,
    healthScore: 31,
    failureRiskDays: [11, 19],
    seasonalRiskScore: 88,
    populationAffected: 4200,
    urgency: 9,
    dependencies: ['R-41', 'B-17'],
    barrierState: 'lowered',
    telemetry: [
      { label: 'Water Level', value: '82', unit: '%', status: 'critical' },
      { label: 'Flow Rate', value: '0.4', unit: 'm³/s', status: 'elevated' },
      { label: 'Turbidity', value: '610', unit: 'NTU', status: 'critical' },
      { label: 'H2S Gas', value: '48', unit: 'ppm', status: 'elevated' },
      { label: 'Sediment', value: '67', unit: '%', status: 'critical' },
    ],
    costBreakdown: [
      { label: 'De-silting & Cleaning', amount: 25000 },
      { label: 'Skilled + Unskilled Labour', amount: 15000 },
      { label: 'Heavy Equipment (Jetting)', amount: 10000 },
      { label: 'Waste Logistics & Disposal', amount: 5000 },
    ],
    repairReplace: [
      { mode: 'repair', cost: 55000, lifeExtension: '+7 months', notes: 'Jetting +局部 patch lining' },
      { mode: 'replace', cost: 810000, lifeExtension: '+15 years', notes: 'Full RCC box reconstruction' },
    ],
    verdict: 'Repair immediately; replace before next monsoon cycle.',
  },
  {
    id: 'D-204',
    category: 'drain',
    name: 'Drain D-204',
    ward: 'Ward 2 — Industrial',
    location: { x: 62, y: 34 },
    ageYears: 8,
    material: 'HDPE Lined',
    installedYear: 2017,
    healthScore: 68,
    failureRiskDays: [42, 60],
    seasonalRiskScore: 54,
    populationAffected: 1800,
    urgency: 5,
    dependencies: ['R-12'],
    barrierState: 'normal',
    telemetry: [
      { label: 'Water Level', value: '41', unit: '%', status: 'normal' },
      { label: 'Flow Rate', value: '1.8', unit: 'm³/s', status: 'normal' },
      { label: 'Turbidity', value: '120', unit: 'NTU', status: 'normal' },
      { label: 'H2S Gas', value: '12', unit: 'ppm', status: 'normal' },
      { label: 'Sediment', value: '23', unit: '%', status: 'normal' },
    ],
    costBreakdown: [
      { label: 'De-silting & Cleaning', amount: 14000 },
      { label: 'Skilled + Unskilled Labour', amount: 9000 },
      { label: 'Heavy Equipment', amount: 6000 },
      { label: 'Waste Disposal', amount: 3000 },
    ],
    repairReplace: [
      { mode: 'repair', cost: 32000, lifeExtension: '+10 months', notes: 'Routine jetting' },
      { mode: 'replace', cost: 420000, lifeExtension: '+20 years', notes: 'HDPE relining' },
    ],
    verdict: 'Routine maintenance sufficient this quarter.',
  },
  {
    id: 'D-318',
    category: 'drain',
    name: 'Drain D-318',
    ward: 'Ward 7 — Old Town',
    location: { x: 48, y: 72 },
    ageYears: 22,
    material: 'Brick Masonry',
    installedYear: 2003,
    healthScore: 22,
    failureRiskDays: [5, 9],
    seasonalRiskScore: 94,
    populationAffected: 6100,
    urgency: 10,
    dependencies: ['R-58', 'SP-184'],
    barrierState: 'emergency',
    telemetry: [
      { label: 'Water Level', value: '94', unit: '%', status: 'critical' },
      { label: 'Flow Rate', value: '0.1', unit: 'm³/s', status: 'critical' },
      { label: 'Turbidity', value: '880', unit: 'NTU', status: 'critical' },
      { label: 'CH4 Gas', value: '71', unit: 'ppm', status: 'critical' },
      { label: 'Sediment', value: '89', unit: '%', status: 'critical' },
    ],
    costBreakdown: [
      { label: 'Emergency De-silting', amount: 48000 },
      { label: 'Labour (24h shift)', amount: 28000 },
      { label: 'Vacuum Truck + Jetting', amount: 22000 },
      { label: 'Hazardous Waste Disposal', amount: 14000 },
    ],
    repairReplace: [
      { mode: 'repair', cost: 112000, lifeExtension: '+4 months', notes: 'Emergency desilt + structural shoring' },
      { mode: 'replace', cost: 1240000, lifeExtension: '+25 years', notes: 'RCC replacement of brick drain' },
    ],
    verdict: 'EMERGENCY: Replace recommended. Risk of street collapse.',
  },

  // ---------- PIPES ----------
  {
    id: 'P-43',
    category: 'pipe',
    name: 'Pipeline P-43',
    ward: 'Ward 4 — Riverside',
    location: { x: 28, y: 50 },
    ageYears: 19,
    material: 'CI Ductile Iron',
    installedYear: 2006,
    healthScore: 44,
    failureRiskDays: [18, 30],
    seasonalRiskScore: 61,
    populationAffected: 3200,
    urgency: 7,
    dependencies: ['D-102'],
    telemetry: [
      { label: 'Pressure', value: '2.1', unit: 'bar', status: 'elevated' },
      { label: 'Acoustic Leak', value: '38', unit: 'dB', status: 'elevated' },
      { label: 'Flow Delta', value: '-14', unit: '%', status: 'elevated' },
      { label: 'pH', value: '6.2', unit: '', status: 'normal' },
    ],
    costBreakdown: [
      { label: 'Pipe Section Material', amount: 145000 },
      { label: 'Skilled Welding Labour', amount: 62000 },
      { label: 'Trenching Equipment', amount: 33000 },
      { label: 'Disposal & Backfill', amount: 12000 },
    ],
    repairReplace: [
      { mode: 'repair', cost: 240000, lifeExtension: '+7 months', notes: 'Clamp + sleeve repair' },
      { mode: 'replace', cost: 810000, lifeExtension: '+15 years', notes: 'Full segment replacement' },
    ],
    verdict: 'Replace recommended due to high internal pipe corrosion and structural age.',
  },
  {
    id: 'P-88',
    category: 'pipe',
    name: 'Pipeline P-88',
    ward: 'Ward 1 — Civic Center',
    location: { x: 54, y: 48 },
    ageYears: 6,
    material: 'HDPE',
    installedYear: 2019,
    healthScore: 81,
    failureRiskDays: [120, 180],
    seasonalRiskScore: 22,
    populationAffected: 900,
    urgency: 2,
    dependencies: [],
    telemetry: [
      { label: 'Pressure', value: '3.4', unit: 'bar', status: 'normal' },
      { label: 'Acoustic Leak', value: '11', unit: 'dB', status: 'normal' },
      { label: 'Flow Delta', value: '+1', unit: '%', status: 'normal' },
      { label: 'pH', value: '7.1', unit: '', status: 'normal' },
    ],
    costBreakdown: [
      { label: 'Material', amount: 28000 },
      { label: 'Labour', amount: 14000 },
      { label: 'Equipment', amount: 8000 },
      { label: 'Disposal', amount: 3000 },
    ],
    repairReplace: [
      { mode: 'repair', cost: 53000, lifeExtension: '+18 months', notes: 'Preventive' },
      { mode: 'replace', cost: 240000, lifeExtension: '+30 years', notes: 'Not warranted' },
    ],
    verdict: 'Healthy. No action required.',
  },

  // ---------- ROADS (with 10m RQI segments) ----------
  {
    id: 'R-41',
    category: 'road',
    name: 'Road Segment R-41',
    ward: 'Ward 4 — Riverside',
    location: { x: 34, y: 60 },
    ageYears: 5,
    material: 'Bituminous Concrete',
    installedYear: 2020,
    healthScore: 38,
    failureRiskDays: [14, 24],
    seasonalRiskScore: 79,
    populationAffected: 4200,
    urgency: 8,
    dependencies: ['B-17'],
    telemetry: [
      { label: 'IRI Roughness', value: '6.8', unit: 'm/km', status: 'critical' },
      { label: 'Rutting Depth', value: '14', unit: 'mm', status: 'elevated' },
      { label: 'Crack Density', value: '22', unit: '%', status: 'elevated' },
    ],
    rqiSegments: [
      { start: 0, end: 10, score: 7 },
      { start: 10, end: 20, score: 5 },
      { start: 20, end: 30, score: 3, defect: 'Pothole cluster + alligator cracking' },
      { start: 30, end: 40, score: 4, defect: 'Edge break + rutting' },
      { start: 40, end: 50, score: 6 },
    ],
    nearMissEvents: 7,
    costBreakdown: [
      { label: 'Bituminous Material', amount: 185000 },
      { label: 'Paving Crew Labour', amount: 74000 },
      { label: 'Paver + Roller Equipment', amount: 45000 },
      { label: 'Milling Waste Disposal', amount: 18000 },
    ],
    repairReplace: [
      { mode: 'repair', cost: 322000, lifeExtension: '+12 months', notes: 'Overlay + pothole patching' },
      { mode: 'replace', cost: 980000, lifeExtension: '+12 years', notes: 'Full-depth reconstruction' },
    ],
    verdict: 'Repair overlay now; plan full reconstruction next fiscal year.',
  },
  {
    id: 'R-12',
    category: 'road',
    name: 'Road Segment R-12',
    ward: 'Ward 2 — Industrial',
    location: { x: 66, y: 38 },
    ageYears: 3,
    material: 'Concrete Rigid',
    installedYear: 2022,
    healthScore: 72,
    failureRiskDays: [60, 90],
    seasonalRiskScore: 35,
    populationAffected: 1800,
    urgency: 3,
    dependencies: [],
    telemetry: [
      { label: 'IRI Roughness', value: '3.1', unit: 'm/km', status: 'normal' },
      { label: 'Rutting Depth', value: '3', unit: 'mm', status: 'normal' },
      { label: 'Crack Density', value: '5', unit: '%', status: 'normal' },
    ],
    rqiSegments: [
      { start: 0, end: 10, score: 8 },
      { start: 10, end: 20, score: 9 },
      { start: 20, end: 30, score: 7 },
      { start: 30, end: 40, score: 8 },
    ],
    nearMissEvents: 2,
    costBreakdown: [
      { label: 'Joint Seal Material', amount: 22000 },
      { label: 'Labour', amount: 12000 },
      { label: 'Equipment', amount: 7000 },
      { label: 'Disposal', amount: 2000 },
    ],
    repairReplace: [
      { mode: 'repair', cost: 43000, lifeExtension: '+24 months', notes: 'Joint resealing' },
      { mode: 'replace', cost: 640000, lifeExtension: '+20 years', notes: 'Not warranted' },
    ],
    verdict: 'Healthy. Routine joint maintenance only.',
  },
  {
    id: 'R-58',
    category: 'road',
    name: 'Road Segment R-58',
    ward: 'Ward 7 — Old Town',
    location: { x: 50, y: 68 },
    ageYears: 11,
    material: 'Bituminous',
    installedYear: 2014,
    healthScore: 28,
    failureRiskDays: [6, 12],
    seasonalRiskScore: 91,
    populationAffected: 6100,
    urgency: 10,
    dependencies: ['SP-184'],
    telemetry: [
      { label: 'IRI Roughness', value: '9.2', unit: 'm/km', status: 'critical' },
      { label: 'Rutting Depth', value: '22', unit: 'mm', status: 'critical' },
      { label: 'Crack Density', value: '41', unit: '%', status: 'critical' },
    ],
    rqiSegments: [
      { start: 0, end: 10, score: 4 },
      { start: 10, end: 20, score: 2, defect: 'Severe pothole + subbase failure' },
      { start: 20, end: 30, score: 3, defect: 'Alligator cracking widespread' },
      { start: 30, end: 40, score: 5 },
      { start: 40, end: 50, score: 2, defect: 'Pothole + water ponding' },
    ],
    nearMissEvents: 14,
    costBreakdown: [
      { label: 'BC Material', amount: 240000 },
      { label: 'Paving Crew', amount: 96000 },
      { label: 'Equipment', amount: 58000 },
      { label: 'Disposal', amount: 26000 },
    ],
    repairReplace: [
      { mode: 'repair', cost: 420000, lifeExtension: '+8 months', notes: 'Deep patch + overlay' },
      { mode: 'replace', cost: 1450000, lifeExtension: '+15 years', notes: 'Full reconstruction + subbase' },
    ],
    verdict: 'EMERGENCY: Full reconstruction recommended. Subbase compromised.',
  },

  // ---------- SMART POLES ----------
  {
    id: 'SP-184',
    category: 'pole',
    name: 'Smart Pole SP-184',
    ward: 'Ward 7 — Old Town',
    location: { x: 52, y: 66 },
    ageYears: 4,
    material: 'Galvanized Steel',
    installedYear: 2021,
    healthScore: 35,
    failureRiskDays: [9, 16],
    seasonalRiskScore: 70,
    populationAffected: 2100,
    urgency: 8,
    dependencies: ['R-58'],
    telemetry: [
      { label: 'Tilt Angle', value: '4.2', unit: '°', status: 'critical' },
      { label: 'Vibration', value: '0.8', unit: 'g', status: 'elevated' },
      { label: 'Illumination', value: 'OFF', unit: '', status: 'critical' },
      { label: 'Impact Events', value: '3', unit: 'evt', status: 'critical' },
    ],
    poleStrikes: 3,
    nearMissEvents: 11,
    costBreakdown: [
      { label: 'Pole + Arm Material', amount: 78000 },
      { label: 'Electrical + Lighting', amount: 34000 },
      { label: 'Installation Labour', amount: 18000 },
      { label: 'Old Pole Disposal', amount: 6000 },
    ],
    repairReplace: [
      { mode: 'repair', cost: 136000, lifeExtension: '+6 months', notes: 'Straighten + base reinforcement' },
      { mode: 'replace', cost: 214000, lifeExtension: '+18 years', notes: 'New smart pole + sensors' },
    ],
    verdict: 'Replace recommended. Repeated vehicle impacts detected.',
  },
  {
    id: 'SP-77',
    category: 'pole',
    name: 'Smart Pole SP-77',
    ward: 'Ward 1 — Civic Center',
    location: { x: 56, y: 44 },
    ageYears: 2,
    material: 'Aluminum',
    installedYear: 2023,
    healthScore: 86,
    failureRiskDays: [200, 300],
    seasonalRiskScore: 15,
    populationAffected: 600,
    urgency: 1,
    dependencies: [],
    telemetry: [
      { label: 'Tilt Angle', value: '0.3', unit: '°', status: 'normal' },
      { label: 'Vibration', value: '0.1', unit: 'g', status: 'normal' },
      { label: 'Illumination', value: 'ON', unit: '', status: 'normal' },
      { label: 'Motion Dimming', value: 'Active', unit: '', status: 'normal' },
    ],
    poleStrikes: 0,
    nearMissEvents: 1,
    costBreakdown: [
      { label: 'Material', amount: 18000 },
      { label: 'Electrical', amount: 8000 },
      { label: 'Labour', amount: 5000 },
      { label: 'Disposal', amount: 2000 },
    ],
    repairReplace: [
      { mode: 'repair', cost: 33000, lifeExtension: '+24 months', notes: 'Preventive' },
      { mode: 'replace', cost: 180000, lifeExtension: '+20 years', notes: 'Not warranted' },
    ],
    verdict: 'Healthy. Motion-dimming active.',
  },

  // ---------- BRIDGES ----------
  {
    id: 'B-17',
    category: 'bridge',
    name: 'Bridge B-17',
    ward: 'Ward 4 — Riverside',
    location: { x: 26, y: 44 },
    ageYears: 27,
    material: 'PSC Box Girder',
    installedYear: 1998,
    healthScore: 41,
    failureRiskDays: [22, 35],
    seasonalRiskScore: 72,
    populationAffected: 8400,
    urgency: 9,
    dependencies: ['R-41'],
    barrierState: 'normal',
    telemetry: [
      { label: 'Tilt', value: '0.8', unit: '°', status: 'elevated' },
      { label: 'Vibration', value: '1.2', unit: 'Hz', status: 'elevated' },
      { label: 'Pier Scour', value: '18', unit: 'cm', status: 'critical' },
      { label: 'River Level', value: '7.2', unit: 'm', status: 'elevated' },
    ],
    costBreakdown: [
      { label: 'Structural Material', amount: 1850000 },
      { label: 'Specialist Engineering Labour', amount: 640000 },
      { label: 'Heavy Equipment', amount: 380000 },
      { label: 'Waste & Site Cleanup', amount: 90000 },
    ],
    repairReplace: [
      { mode: 'repair', cost: 2960000, lifeExtension: '+5 years', notes: 'Pier scour protection + bearing replacement' },
      { mode: 'replace', cost: 12400000, lifeExtension: '+50 years', notes: 'Full bridge reconstruction' },
    ],
    verdict: 'Repair: scour protection urgent. Monitor river levels pre-monsoon.',
  },
  {
    id: 'B-3',
    category: 'bridge',
    name: 'Bridge B-3',
    ward: 'Ward 2 — Industrial',
    location: { x: 70, y: 30 },
    ageYears: 12,
    material: 'Steel Truss',
    installedYear: 2013,
    healthScore: 75,
    failureRiskDays: [90, 150],
    seasonalRiskScore: 38,
    populationAffected: 2600,
    urgency: 3,
    dependencies: [],
    barrierState: 'normal',
    telemetry: [
      { label: 'Tilt', value: '0.2', unit: '°', status: 'normal' },
      { label: 'Vibration', value: '0.6', unit: 'Hz', status: 'normal' },
      { label: 'Pier Scour', value: '3', unit: 'cm', status: 'normal' },
      { label: 'River Level', value: '4.1', unit: 'm', status: 'normal' },
    ],
    costBreakdown: [
      { label: 'Protective Coating', amount: 220000 },
      { label: 'Labour', amount: 110000 },
      { label: 'Equipment', amount: 60000 },
      { label: 'Disposal', amount: 18000 },
    ],
    repairReplace: [
      { mode: 'repair', cost: 408000, lifeExtension: '+8 years', notes: 'Repainting + bolt tightening' },
      { mode: 'replace', cost: 8400000, lifeExtension: '+50 years', notes: 'Not warranted' },
    ],
    verdict: 'Healthy. Routine protective coating cycle.',
  },
];

export const CASCADE_LINKS: CascadeLink[] = [
  { fromId: 'D-102', toId: 'R-41', label: 'Water accumulation → subbase deterioration', costIfIgnored: 1850000 },
  { fromId: 'D-102', toId: 'B-17', label: 'Scour acceleration at pier foundations', costIfIgnored: 2960000 },
  { fromId: 'P-43', toId: 'D-102', label: 'Pipe burst inflow overloads drain', costIfIgnored: 550000 },
  { fromId: 'D-318', toId: 'R-58', label: 'Severe flooding → road washout', costIfIgnored: 1450000 },
  { fromId: 'D-318', toId: 'SP-184', label: 'Waterlogging → pole base corrosion', costIfIgnored: 214000 },
  { fromId: 'R-41', toId: 'B-17', label: 'Traffic diversion → increased load on bridge', costIfIgnored: 1200000 },
  { fromId: 'R-58', toId: 'SP-184', label: 'Road degradation → pole impact risk', costIfIgnored: 214000 },
  { fromId: 'B-17', toId: 'R-41', label: 'Bridge closure → road overload', costIfIgnored: 420000 },
];

export const WARDS = [
  'Ward 1 — Civic Center',
  'Ward 2 — Industrial',
  'Ward 3 — Lakeside',
  'Ward 4 — Riverside',
  'Ward 5 — Tech Park',
  'Ward 6 — Green Valley',
  'Ward 7 — Old Town',
];

export const CV_DEFECT_LIBRARY = [
  { type: 'Pothole', confidence: 0.94, severity: 'high' as const, estDimensions: '1.2m × 0.8m × 0.15m' },
  { type: 'Alligator Cracking', confidence: 0.88, severity: 'high' as const, estDimensions: '3.5m² area' },
  { type: 'Pipe Root Intrusion', confidence: 0.91, severity: 'medium' as const, estDimensions: 'Ø180mm, 40% blockage' },
  { type: 'Joint Crack', confidence: 0.79, severity: 'medium' as const, estDimensions: '2.1m length' },
  { type: 'Edge Break', confidence: 0.83, severity: 'medium' as const, estDimensions: '0.6m × 0.3m' },
  { type: 'Rutting', confidence: 0.86, severity: 'low' as const, estDimensions: '18mm depth' },
  { type: 'Illegal Dumping', confidence: 0.97, severity: 'high' as const, estDimensions: '2.4m³ debris' },
];

export function assetById(id: string): Asset | undefined {
  return ASSETS.find((a) => a.id === id);
}

export function totalCostOf(asset: Asset): number {
  return asset.costBreakdown.reduce((s, c) => s + c.amount, 0);
}

export function cheapestOption(asset: Asset): number {
  return Math.min(...asset.repairReplace.map((r) => r.cost));
}
